import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import axios from 'axios';
import { useEffect, useState } from 'react';
import baseUrl from '../services/baseUrl.js';

export default function Bets({ filter }) {
	console.log(filter);
	const [bets, setBets] = useState([]);
	axios
		.get(baseUrl + 'api/bets?filter=' + JSON.stringify(filter))
		.then((res) => {
			console.log(res.data);
			setBets(res.data);
		});
	return (
		<div className={styles.container}>
			<Head>
				<title>Bet University</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.grid}>
					{bets.map((bet) => {
						return (
							<>
								<Link key={bet._id} href="/" className={styles.card}>
									<a>
										<h3>{bet.event_id}</h3>
										<p>{`team1: ${bet.odds[0]}, team2: ${bet.odds[1]}, tie: ${bet.odds[2]}`}</p>
									</a>
								</Link>
							</>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
