import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from "react"
import axios from 'axios'
import { supabase } from '../services/supabaseClient'

export default function Home() {

  const [selectedCard, setSelectedCard] = useState()
  const [betValue, setBetValue] = useState(0)
  const [selectedOdd, setSelectedOdd] = useState()
  const [events, setEvents] = useState([
      {
        teams: ["FGV", "FEI"],
        odds: [3.2, 1.5, 2.5], 
        name: "Final Futebol 4",
        modality: 'Futebol',
        eventId: "62290cc1b0b144013565945f"
      },
      {
        teams: ["DFG", "ABC"],
        odds: [2.1, 2.2, 3.5], 
        name: "Final Futebol 3",
        modality: 'Futebol',
        eventId: "9"
      },
      {
        teams: ["USP", "DEW"],
        odds: [1.7, 2.2, 1.5], 
        name: "Final Futebol 2",
        modality: 'Futebol',
        eventId: "30"
      },
      {
        teams: ["LEU", "ABC"],
        odds: [2.2, 3.2, 2.7], 
        name: "Final Futebol 1",
        modality: 'Futebol',
        eventId: "12"
      },
      
  ])
  const [data, setData] = useState(null)
  const [user, setUsers] = useState({})
  const [logged, setLogged] = useState(false)

  useEffect(()=>{
    getData()
  },[])

  function Login(){
    supabase.auth.signIn({
      provider: 'google',
    }).then((res)=>{
      setLogged(true)
    })
  }

  function getData(){
    if(!window.localStorage.getItem('supabase.auth.token')){
      Login()
    }else{
      setLogged(true)
    }
    setData(true)
    axios.get('/api/events').then(res=>{
      setEvents(res.data)
    })
    const supabaseSession = JSON.parse(window.localStorage.getItem('supabase.auth.token'))
    console.log(supabaseSession.currentSession.user.email)
    const user = supabaseSession.currentSession.user
    axios.get(`/api/users?filter={"email": ${user.email}}`).then(res=>{
      console.log(res)
      setUsers(res.data[0])
    }).catch(err=>console.log(err))
    // axios.get(`/api/users?filter={"id":"6227760eaa2b6113c552d91a"}`).then(res=>{
    //   console.log(res)
    //   setUsers(res.data[0])
    // }).catch(err=>console.log(err))
  }
  function bet(card, odd){
    const newUser = user
    newUser.wallet = user.wallet - (betValue * card.odds.indexOf(odd))
    console.log(newUser)
    setUsers(newUser)
    axios.post('/api/create-bet', {
      user_id: 1, 
      event_id: card._id, 
      modality: card.modality, 
      odds: card.odds, 
      bet: card.odds.indexOf(odd), 
      bet_value: betValue, 
      offer: false
    })
    .then(res=>{
    })
  }
  return (
    <div className={styles.container}>
      {logged?(<>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      User: {user.wallet}
      <main className={styles.main}>
        {selectedCard?<div className={styles.selectedCard}>
          <h2>{selectedCard.name} - {selectedCard.teams[selectedOdd]}</h2>
          <p>Odd: {selectedOdd}</p>
          <input onChange={e=>setBetValue(Number(e.target.value))} type="number" placeholder='Valor apostado em reais'/>
          <p>Retorno esperado: R${(Number(selectedOdd)*betValue).toFixed(2)}</p>
          {betValue>0?<button onClick={()=>bet(selectedCard, selectedOdd)}>Apostar</button>:null}
        </div>:null}


        <div className={styles.grid}>
          {
            events.map(event=>(
              <div key={event._id} className={styles.event} onClick={()=>setSelectedCard(event)}>
                <h2>{event.name}</h2>
                <p>{`${event.teams[0]} X ${event.teams[1]}`}</p>
                <button onClick={()=>{setSelectedCard(event);setSelectedOdd(event.odds[0])}}>{event.odds[0]}</button> X <button onClick={()=>{setSelectedCard(event);setSelectedOdd(event.odds[1])}}>{event.odds[1]}</button> X <button onClick={()=>{setSelectedCard(event);setSelectedOdd(event.odds[2])}}>{event.odds[2]}</button>
              </div>
            ))
          }
         
            
        </div>
      </main>
      </>
      ):(
        <button onClick={Login}>
          Login...
        </button>
      )}
    </div>
  )
}
