import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react"

export default function Home() {

  const [events, setEvents] = useState([
      {
        teams: ["FGV", "FEI"],
        odds: [3.2, 1.5, 2.5], 
        name: "Final Futebol 4",
        eventId: "15"
      },
      {
        teams: ["DFG", "ABC"],
        odds: [2.1, 2.2, 3.5], 
        name: "Final Futebol 3",
        eventId: "9"
      },
      {
        teams: ["USP", "DEW"],
        odds: [1.7, 2.2, 1.5], 
        name: "Final Futebol 2",
        eventId: "30"
      },
      {
        teams: ["LEU", "ABC"],
        odds: [2.2, 3.2, 2.7], 
        name: "Final Futebol 1",
        eventId: "12"
      },
      
  ])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        


        <div className={styles.grid}>
          {
            events.map(event=>(
              <div classname={styles.event}>
              <h2>{event.name}</h2>
              <p>{`${event.teams[0]} X ${event.teams[1]}`}</p>
              </div>
            ))
          }
         
            
        </div>
      </main>

      
    </div>
  )
}
